#!/bin/sh

get_syala() {
    COUNT=`cat ~/syala`
    if [ ${COUNT} -lt 6 ] ; then
        echo $((COUNT++)) > ~/syala
    else
        COUNT=1
        echo 1 > ~/syala
    fi

    case ${COUNT} in
        1 ) SYALA="( ˘ω˘ )" ;;
        2 ) SYALA="(  ˘ω˘)" ;;
        3 ) SYALA="(   ˘ω)" ;;
        4 ) SYALA="(    ˘)" ;;
        5 ) SYALA="(˘    )" ;;
        6 ) SYALA="(ω˘   )" ;;
        7 ) SYALA="(˘ω˘  )" ;;
    esac

    echo "${SYALA}"
}
