set -g prefix C-q
unbind C-b

bind r source-file ~/.tmux.conf

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind | split-window -h
bind - split-window -v

set-option -g status-position top

